#!/bin/sh

MD_PATH="course-note/"
OUT_PATH="public/"
NOW=$(TZ=Europe/Moscow date +"%d %b %Y %H:%M")

if [ -z "$1" ]; then
  MD_FILES=$(find $MD_PATH -type f -name "*.md" | sort)
else
  MD_FILES="course-note/00-info.md $1"
fi

mkdir -p $OUT_PATH

pandoc -D latex > template.tex

cat > replacement.txt << 'EOF'
\usepackage{listings}
\\newcommand{\passthrough}[1]{#1}
\lstset{defaultdialect=[5.3]Lua}
\lstset{defaultdialect=[x86masm]Assembler}
\lstset{inputencoding=utf8,extendedchars=true}
\lstset{
  showstringspaces=false,
}
\makeatletter
\lst@InputCatcodes
\def\lst@DefEC{%
 \lst@CCECUse \lst@ProcessLetter
  ^^^^0401
  ^^^^0410
  ^^^^0411
  ^^^^0412
  ^^^^0413
  ^^^^0414
  ^^^^0415
  ^^^^0416
  ^^^^0417
  ^^^^0418
  ^^^^0419
  ^^^^041a
  ^^^^041b
  ^^^^041c
  ^^^^041d
  ^^^^041e
  ^^^^041f
  ^^^^0420
  ^^^^0421
  ^^^^0422
  ^^^^0423
  ^^^^0424
  ^^^^0425
  ^^^^0426
  ^^^^0427
  ^^^^0428
  ^^^^0429
  ^^^^042a
  ^^^^042b
  ^^^^042c
  ^^^^042d
  ^^^^042e
  ^^^^042f
  ^^^^0430
  ^^^^0431
  ^^^^0432
  ^^^^0433
  ^^^^0434
  ^^^^0435
  ^^^^0436
  ^^^^0437
  ^^^^0438
  ^^^^0439
  ^^^^043a
  ^^^^043b
  ^^^^043c
  ^^^^043d
  ^^^^043e
  ^^^^043f
  ^^^^0440
  ^^^^0441
  ^^^^0442
  ^^^^0443
  ^^^^0444
  ^^^^0445
  ^^^^0446
  ^^^^0447
  ^^^^0448
  ^^^^0449
  ^^^^044a
  ^^^^044b
  ^^^^044c
  ^^^^044d
  ^^^^044e
  ^^^^044f
  ^^^^0451
  ^^00}
\lst@RestoreCatcodes
\makeatother
EOF

awk -v replacement="$(cat replacement.txt)" '
  /\$if\(listings\)\$/ {
    print
    print replacement
    in_block = 1
    next
  }
  /\$endif\$/ {
    in_block = 0
    print
    next
  }
  !in_block {
    print
  }
' template.tex > template.tmp && mv template.tmp template.tex

pandoc $MD_FILES -o $OUT_PATH/csa-notes.pdf \
  --pdf-engine=xelatex --template=template.tex \
  --table-of-contents --number-sections \
  --listings

rm template.tex replacement.txt
